### ISSUE TITLE
How t use this library for logIn and signUp functionality?

### ISSUE THREAD

**Issue by karanthakakr04** [steelkiwi/SeparateShapesView#1]
I am trying to make this library work for logIn and signUp functionality. I did it like this:

```
@Override
    public boolean onLeftButtonClick() {
        Intent intent = new Intent(MainActivity.this, SignIn.class);
        startActivity(intent);
        return true;
    }

    @Override
    public boolean onRightButtonClick() {
        Intent intent = new Intent(MainActivity.this, SignUp.class);
        startActivity(intent);
        return true;
    }
```
which gave me an error as follows:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: app.example.com.radiobutton, PID: 15760
                                                                             android.content.ActivityNotFoundException: Unable to find explicit activity class {app.example.com.radiobutton/app.example.com.radiobutton.SignIn}; have you declared this activity in your AndroidManifest.xml?
                                                                                 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
                                                                                 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                                                                                 at android.app.Activity.startActivityForResult(Activity.java:3930)
                                                                                 at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                                 at android.app.Activity.startActivityForResult(Activity.java:3890)
                                                                                 at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                                 at android.app.Activity.startActivity(Activity.java:4213)
                                                                                 at android.app.Activity.startActivity(Activity.java:4181)
                                                                                 at app.example.com.radiobutton.MainActivity.onLeftButtonClick(MainActivity.java:66)
                                                                                 at com.steelkiwi.library.SeparateShapesView.onLeftButtonClick(SeparateShapesView.java:239)
                                                                                 at com.steelkiwi.library.SeparateShapesView.onTouch(SeparateShapesView.java:226)
                                                                                 at com.steelkiwi.library.SeparateShapesView.onTouch(SeparateShapesView.java:203)
                                                                                 at android.view.View.dispatchTouchEvent(View.java:9296)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                 at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                 at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                 at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                             	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:58

```
What am I doing wrong here? 
From my understanding of this library it animates on button press so do I need to do this task on Threads?
Any help would be appreciated.

**Comment by polyak01** [comment]
Please use StackOverflow for usage questions & check your manifest)
